CREATE TABLE Person (
                        id INT GENERATED by default AS IDENTITY PRIMARY KEY,
                        full_name VARCHAR(100) NOT NULL UNIQUE,
                        year_of_birth INT NOT NULL
);

CREATE TABLE Book (
                      id INT GENERATED by default AS IDENTITY PRIMARY KEY,
                      title VARCHAR(100) NOT NULL,
                      author VARCHAR(100) NOT NULL,
                      year INT NOT NULL,
                      person_id INT DEFAULT NULL,
                      FOREIGN KEY (person_id) REFERENCES Person(id) ON DELETE SET NULL
);